version: "3.8"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local

services:
  spark-master:
    image: spark-master
    deploy:
      resources:
        limits:
          memory: 1g
    container_name: spark-master
    ports:
      - 8083:8080
      - 7077:7077
      - 4041:4040
    volumes:
      - shared-workspace:/opt/workspace

  spark-worker-1:
    image: spark-worker
    deploy:
      resources:
        limits:
          memory: 26g
    container_name: spark-worker-1
    environment:
      SPARK_WORKER_CORES: "8"
      SPARK_WORKER_MEMORY: "24g"
      SPARK_DRIVER_MEMORY: "22g"
      SPARK_EXECUTOR_CORES: "5"
      SPARK_EXECUTOR_MEMORY: "20g"
    ports:
      - 8084:8081
      - 4042:4040
    volumes:
      - shared-workspace:/opt/workspace
      - ./volume/adtdata:/home/jovyan/work/adtdata
    depends_on:
      - spark-master

  jupyter-pathling:
    container_name: jupyter-pathling
    image: jupyter-pathling
    ports:
      - 4040:4040
      - 8888:8888
    volumes:
      - ./volume:/home/jovyan/work
